# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=500)),
                ('product_url', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
